name: Python application release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cx-Freeze

    - name: Build with cx-Freeze
      run: |
        cxfreeze -c tarkov_logs.py --target-dir dist

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: tarkov-log-reader
        path: dist/tarkov_logs.exe

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/tarkov_logs.exe
        asset_name: tarkov_logs.exe
        asset_content_type: application/octet-stream
